connection:
  file_system: local
  input_file_paths: ["oxford-government-response.csv"]
  input_format: csv
  output_dir_path: output


columns:
  - location_key
  - school_closing
  - cancel_public_events
#  - restrictions_on_gatherings
#  - public_transport_closing
date_column: date
aggregations:
  - name: total_income_support
    formula: sum(income_support)
#  - name: total_international_support
#    formula: sum(international_support)
#  - name: total_fiscal_measures
#    formula: sum(fiscal_measures)
granularity: daily
no_of_dimensions: 2


